CREATE  PROCEDURE CACBAIVIET_DUOC_DUYET_QUA
AS
SELECT * FROM POST WHERE XET_DUYET = 1;
-- CÁC BÀI VIẾT ĐÃ ĐƯỢC DUYỆT
EXEC CACBAIVIET_DUOC_DUYET_QUA;

CREATE PROCEDURE CACBAIVIET_KHONG_DUOC_DUYET
AS
SELECT * FROM POST WHERE XET_DUYET = 0;
-- CÁC BÀI VIẾT KHÔNG CHO PHÉP ĐĂNG
EXEC  CACBAIVIET_KHONG_DUOC_DUYET;

CREATE PROCEDURE CACBAIVIET_CHUA_DUOC_DUYET
AS
SELECT * FROM POST WHERE XET_DUYET IS NULL;
-- CÁC BÀI VIẾT ĐANG CHỜ DUYỆT
EXEC CACBAIVIET_CHUA_DUOC_DUYET;
