SELECT* FROM POST;
SELECT*FROM MANAGERS;
-- CÁC CÂU TRU VẤN KHÔNG ĐIỀU KIỆN TRẢ VỀ MỘT BẢNG ĐẦY ĐỦ
SELECT * FROM POST WHERE LUOT_XEM >= 20 ;
-- CÂU TRUY VẤN CÓ ĐIỀU KIỆN TRẢ VỀ MỘT BẢNG ĐẦY ĐỦ
SELECT TIEU_DE , NOI_DUNG , LUOT_XEM , XET_DUYET ,NGUOI_DUYET
FROM POST
WHERE XET_DUYET = 1 ;
-- CHỌN RA CÁC POST ĐÃ ĐƯỢC XÉT DUYỆT
SELECT TIEU_DE , NOI_DUNG , LUOT_XEM , XET_DUYET ,NGUOI_DUYET, THOI_GIAN_DANG
FROM POST
WHERE XET_DUYET = 1 
ORDER BY  TIEU_DE  ;
-- XẮP XẾP KẾT QUẢ THEO THỨ TỰ BẢNG CHỮ CÁI CỘT TIÊU ĐỀ
SELECT COMMENT.NGUOI_COMMENT, POST.TIEU_DE, POST.NOI_DUNG
FROM COMMENT
INNER JOIN POST ON COMMENT.NGUOI_COMMENT = POST.ID_POST;
-- TRUY VẤN NÀY GIỮA BẢNG NGƯỜI SỬ DỤNG VÀ BẢNG TIÊU ĐỀ XEM CÁC USER NÀO COMMENT POST NÀO.
SELECT  DISTINCT  NGUOI_COMMENT 
FROM COMMENT
WHERE YEAR(TIME_COMMENT) < 2020 ;

-- TRUY VẤN SỬ DỤNG HÀM YEAR ĐỂ CHỌN CÁC COMMENT THEO THỜI GIAN
SELECT * FROM POST
WHERE TIEU_DE LIKE 'g%';
-- TÌM TIÊU ĐỀ BÀI BÁO THEO KÝ TỰ
SELECT * FROM SHARE_POST
WHERE ID_SHARE IN ( SELECT ID_SHARE FROM SHARE WHERE YEAR(TIME_SHARE) < 2019 )
ORDER BY ID_SHARE;

-- SỬ DỤNG TRUY VẤN CON ĐỂ BIẾT CÁC ID_SHARE NÀO 
